apiVersion: v1
kind: ConfigMap
metadata:
  name: jobtracker-config
  namespace: jobtracker
data:
  POSTGRES_HOST: "postgres-service"
  POSTGRES_PORT: "5432"
  KAFKA_BOOTSTRAP_SERVERS: "kafka-service:9092"
  AUTH_SERVICE_URL: "http://auth-service:8081"
  INTERNAL_SECRET: "super-secret-internal-key"
---
apiVersion: v1
kind: Secret
metadata:
  name: jobtracker-secrets
  namespace: jobtracker
type: Opaque
stringData:
  POSTGRES_USER: "tracker_user"
  POSTGRES_PASSWORD: "tracker_password"
  JWT_SECRET: "defaultSecretKeyThatIsAtLeast32BytesLongForHS256MustBeChangedInProd"
  GOOGLE_CLIENT_ID: "placeholder_client_id"
  GOOGLE_CLIENT_SECRET: "placeholder_client_secret"
  GEMINI_API_KEY: "placeholder_api_key"
